### ISSUE TITLE
the question in  DOCX about learn FPGA programming

### ISSUE THREAD

**Issue by Guokangz** [RedPitaya/Documentation#44]
sorry,I got a trouble title.
my question is in programming FPGA:
I follow the DOCX about learn FPGA programming. In 1.3.2.2 make an project section, I got a bitstream file from Vivado 2020.1 and remove it to RP by use ssh command-line. When Load the red_pitaya_top.bit to xdevcfg ，there no LED blinking.
I check bitstream file ,delete in directory and try again，there is no change，I use command-line tool to Check the files under /dev, there is no files named xdevcfg before I remove  bitstream file.When I moved it, there was a white file of xdevcfg.
This is my first time asking questions on github, I think I am not a good questioner,hope you don't mind.

**Comment by Lightsaver7** [comment]
Hello Guokangz,

We are working on updating the Teaching materials to work with the 2.00 OS; The way the FPGA image gets loaded has changed. Please refer to the documentation here:
https://redpitaya.readthedocs.io/en/latest/developerGuide/software/build/fpga/fpga.html#reprogramming-the-fpga-with-a-custom-image

**Comment by Lightsaver7** [comment]
The "xdevcfg" is a special driver on 1.04 OS images and older that takes care of loading the bitstream file into the Zynq FPGA.

In 2.00 OS this has been changed to the "fgpautil" driver.

**Comment by Guokangz** [comment]
> The "xdevcfg" is a special driver on 1.04 OS images and older that takes care of loading the bitstream file into the Zynq FPGA.
> 
> In 2.00 OS this has been changed to the "fgpautil" driver.

Thank you for your help. The reason I closed this issue is that I rolled back 1.04OS and it worked. Maybe I was too careless and didn't check the documentation carefully.
