### ISSUE TITLE
Multiple incompatible definitions of rp_AcqSetTriggerSrc()

### ISSUE THREAD

**Issue by edgar-bonet** [RedPitaya/Documentation#64]
Within the _List of supported SCPI &amp; API commands_, in the section [Acquisition trigger][1] ([source][2]), two versions of the C function `rp_AcqSetTriggerSrc()` are documented:

 * `rp_AcqSetTriggerSrc(rp_acq_trig_src_t source)`, which defines a single source for all channels
 * `rp_AcqSetTriggerSrc(rp_channel_t channel, rp_acq_trig_src_t source)`, used in “split trigger mode”.

This is impossible: the C language does not support function overloading. Furthermore, only the first version seems to be [defined in the C API][3].

[1]: https://redpitaya.readthedocs.io/en/latest/appsFeatures/remoteControl/command_list.html#acquisition-trigger
[2]: ../blob/0a3fd44ee0f46bf83eecc3453c6e9bf4ad1c8e09/appsFeatures/remoteControl/command_list.rst?plain=1#L1349-L1357
[3]: ../../RedPitaya/blob/master/rp-api/api/include/rp_acq.h#L126-L134

**Comment by Lightsaver7** [comment]
Hello Edgar,
Thank you for noticing this. This is a typo in the function names. The second function is called `rp_AcqSetTriggerSrcCh(rp_channel_t channel, rp_acq_trig_src_t source)`.
I have fixed the typo in the official docs.

**Comment by edgar-bonet** [comment]
@Lightsaver7: There is no such thing as `rp_AcqSetTriggerSrcCh()`. Other than this issue, [this name does not appear anywhere in any of the Red Pitaya GitHub repos][1].

Should I open another issue for the missing function or could you reopen this one?

[1]: https://github.com/search?q=org%3ARedPitaya+rp_AcqSetTriggerSrcCh&type=code

**Comment by Lightsaver7** [comment]
Ture. The split trigger functionality is still in development (as stated by the “ecosystem” column in the command table) and the development code is not yet available on GitHub. However the function can be used on the latest Nightly Build OS versions.

**Comment by edgar-bonet** [comment]
@Lightsaver7: Is there a publicly available repo with the development version of the code?

If that version is closed source, then I believe the status of the GitHub issues (open/closed) should reflect the state of the publicly available code.

**Comment by Lightsaver7** [comment]
@edgar-bonet 
As it is still in development, no, there is no publicly available development repository. It would be way too chaotic and confusing if we posted everything on GitHub, so we stick with publishing the code for the official OS releases.

We do keep the users in touch with the latest development through the Nightly Builds and updating the documentation ahead of time (marked as “in-dev”).

We will try to keep the status of the GitHub isses in sync with the published code - please see the ecosystem repository for more information. However for this specific issue, I will leave it closed as it is related to a typo and the affected code is currently still closed (so it has minor impact on the situation).
