### ISSUE TITLE
Duplicate label in .rts files

### ISSUE THREAD

**Issue by edgar-bonet** [RedPitaya/Documentation#65]
Building the documentation with the command

```shell
python3 -m sphinx -b dirhtml . $output_dir
```

Produces the following warning:

```text
…/appsFeatures/applications/vna/appVNA.rst:5:
    WARNING: duplicate label vna_extension, other instance in
    …/appsFeatures/applications/pyrpl/pyrpl.rst
```

And indeed, both files start with the line:

```rst
.. _vna_extension:
```

**Comment by Lightsaver7** [comment]
Thank you for letting me know.

The labels are there for easier interlinking between documentation pages. Here is an explanation https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html

I fixed the label by renaming it to `.. _pyrpl::` which is how it should have been from the start.
