### ISSUE TITLE
Incorrect specification: analog output bandwidth

### ISSUE THREAD

**Issue by edgar-bonet** [RedPitaya/Documentation#71]
Among the many changes brought by the October hardware update (#70), there is this hardware specification for the extension connector:

```diff
     +------------------------------------+------------------------------------+
     | Analog output sample rate          | ≲ 3.2 MS/s                         |
     +------------------------------------+------------------------------------+
-    | Analog output bandwidth            | ≈ 160 kHz                          |
+    | Analog output bandwidth            | ≈ 3.2 MS/s                         |
     +------------------------------------+------------------------------------+
     | Communication interfaces           | I2C, SPI, UART, CAN                |
     +------------------------------------+------------------------------------+
```

This is not quite correct. The “bandwidth” is not the same as the sample rate. The sample rate is already specified in the line above, so repeating it here is redundant. The bandwidth is the frequency at which the amplitude drops by 3&nbsp;dB, and is given in hertz, not in samples per second.

I had previously (#62) estimated the cutoff frequency at 160&nbsp;kHz. This estimate is based on the formula

f<sub>c</sub> = log(9) / (2πt<sub>↑</sub>)

where log() is the natural logarithm, and t<sub>↑</sub> is the 10%–90% rise time measured on an oscilloscope. The formula is exact only for a first-order cut-off, but the signal on the scope looked a lot like the output of a first-order low-pass filter.

The affected files are:

```
developerGuide/hardware/122-16/top.rst
developerGuide/hardware/122-16_EXT/top.rst
developerGuide/hardware/125-10/top.rst
developerGuide/hardware/125-14-Z20/top.rst
developerGuide/hardware/125-14/top.rst (twice)
developerGuide/hardware/125-14_4IN/top.rst
developerGuide/hardware/125-14_EXT/top.rst
developerGuide/hardware/125-14_LN/top.rst
developerGuide/hardware/125-14_MULTI/top.rst
developerGuide/hardware/250-12/top.rst
developerGuide/hardware/compares/vs.rst
developerGuide/hardware/hw_specs/extent.rst
```

Note that this specification appears twice in the file `developerGuide/hardware/125-14/top.rst`.

**Comment by Lightsaver7** [comment]
Hello Edgar,
Thank you for pointing it out. I will fix this immediately.

**Comment by Lightsaver7** [comment]
Done
